export let cardsData = [
  {
    text: "🦕",
    background: "#1ed760",
  },
  {text: "🦄",
    background: "#4f26a2",
  },
  {text: "🐯",
    background: "#ff4400",
  },
  {text: "🐦",
    background: "#1ca1f1",
  },
  {text: "🐷",
    background: "#ffccd4",
  },
  {text: "🐢",
    background: "#96a98c",
  },
  {text: "🐪",
    background: "#fed9ad",
  },
  {text: "🐤",
    background: "#fcd000",
  },
  {text: "🐸",
    background: "#006241",
  }
];