export const fake_hcfs = {
  en: [
    {
      id: 1,
      name_en: "Shaer Medical Point",
      name_ar: "نقطة الشاعر الطبية",
      municipal: "Khan Younis",
      govenrate: "Khan Younis",
      partnerType: "Medical Point",
      partner: "UNRWA",
      status: "Partially Functioning",
      served: "Yes",
    },
    {
      id: 2,
      name_en: "Yafa Hospital",
      name_ar: "م. يافا",
      municipal: "Deir Al-Balah",
      govenrate: "Deir Al-Balah",
      partnerType: "Medical Point",
      partner: "Private Institution",
      status: "Partially Functioning",
      served: "No",
    },
  ],
  ar: [
    {
      id: 1,
      name_en: "Shaer Medical Point",
      name_ar: "نقطة الشاعر الطبية",
      municipal: "خانيونس",
      govenrate: "خانيونس	",
      partnerType: "نقطة طبية",
      partner: "UNRWA",
      status: "يعمل جزئيا",
      served: "نعم",
    },
    {
      id: 2,
      name_en: "Yafa Hospital",
      name_ar: "م. يافا",
      municipal: "دير البلح",
      govenrate: "دير البلح",
      partnerType: "نقطة طبية",
      partner: "عيادة خاصة",
      status: "يعمل جزئيا",
      served: "لا",
    },
  ],
};
